### ISSUE TITLE
The title "SAS and R" / sas2r only describes a portion of the document

### ISSUE THREAD

**Issue by esimms999** [Bayer-Group/sas2r#13]
I do not see any SAS code after Chapter 3.1.9. The content then shifts to only R. Still very useful (I like the examples of graphs and code in Chapter 6!). When we get to renv (Chapter 7.1), I can't think of anything in SAS which is similar ... maybe something like git functionality not being available in SAS Studio 3.6 but is available in SAS Studio 3.8?

Should this document be split into a "SAS and R" document and a second document with cool R content/examples?

**Comment by iqis** [comment]
I think this reflects that R's capability being a superset of that of SAS. One would inadvertently talk about something in R that doesn't have a parallel in SAS.

 @robertadamsbayer @mattkumar what do you guys think? Perhaps the original _SAS-to-R_ can be more apt in this regard?

**Comment by robertadamsbayer** [comment]
All valid points. Maybe, at this early stage, we could think of a renaming that reflects the clinical focus a bit more. Maybe something blunt like "Recipes for clinical R" or so?

**Comment by ClaraBeckBayer** [comment]
Dear @esimms999, 

thank you for bringing up this topic.
The motivation for us to create this repository was to support our colleagues in transitioning from the SAS to the R world. And this is also the flow of the bookdown. You might have seen, that we give some initial support where we "translate" SAS syntax into R syntax in the first chapters and then describe how you could get started in R and especially how you would do the typical statistical programming work in R. We assume that our target user group is very much familiar with SAS syntax and wants to learn more about how to do their daily tasks in R. 
If you think, that it is helpful to also add SAS synatx later on in the book and directly compare it to R Syntax please feel more than welcome to do so! We are open for every contribution :-).

**Comment by mattkumar** [comment]
Closed.
