### ISSUE TITLE
Download option not working

### ISSUE THREAD

**Issue by thomas-neitmann** [Bayer-Group/sas2r#16]
When trying to download the book in either `.pdf` or `.epub` format one is directed to the following site and no download is initiated.

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/11788080/213173439-02dc15d2-66f7-4aa6-a273-61d925872c6d.png">

**Comment by iqis** [comment]
Hi, @thomas-neitmann.  Thanks for catching this.  Will fix

**Comment by iqis** [comment]
@mattkumar it seems that a pdf version has to be build explicitly for download. 

I'd argue that _nobody_ ever needs to download a version of this book. Let's remove download altogether.

**Comment by thomas-neitmann** [comment]
Actually someone who *did* want to download a PDF version of the book made me aware that this feature doesn't work di I'd kindly ask you to keep the feature and fix it. Thanks!

**Comment by mattkumar** [comment]
Thanks for raising @thomas-neitmann. I'm surprised as @iqis that the book would be downloaded in an offline format, but I agree if people will use it, we should include it :)

**Comment by iqis** [comment]
https://github.com/Bayer-Group/sas2r/blob/7538d53fe868d82231fb804ee4a9b5f90b4c4faa/03-data.Rmd#L37

This line in Chapter 3 will result in the following error at the step of knitting from LaTeX to PDF.

```
! LaTeX Error: Too deeply nested.
```

**Comment by iqis** [comment]
"you can't change it": according to [this](https://texfaq.org/FAQ-toodeep#:~:text=Too%20deeply%20nested%20This%20error%20appears%20when%20you,of%20the%20nesting%20of%20one%20list%20inside%20another.)

**Comment by mattkumar** [comment]
I don't see a path forward with this, but perhaps we can revisit it if and when we move to Quarto

**Comment by iqis** [comment]
experimented with Quarto, which doesn't (magically) help.
