### ISSUE TITLE
Add GH pages URL to repo description

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [Bayer-Group/sas2r#20]
Missing a link to https://bayer-group.github.io/sas2r/ 😢 

![image](https://user-images.githubusercontent.com/89191115/218106709-e4203b29-7cc8-46db-9135-aacdd7005f5e.png)

**Comment by mattkumar** [comment]
Thanks for the heads up @HenningLorenzen-ext-bayer !

**Comment by iqis** [comment]
fixed.
