### ISSUE TITLE
Handling of missing values

### ISSUE THREAD

**Issue by bundfussr** [Bayer-Group/sas2r#4]
I think a section or some notes regarding handling of missing values would be helpful.

For example, in "Creating new variables" the SAS code and the R code produce different results if `age` is missing. In SAS `AGEGR1` is set to `'<= 50 years old'` while in R it is set to `NA_character_`.

Also `!=` can give unexpected results for SAS programmers. E.g.,
```
  select(adlb, ABLFL != "Y")
```
never returns any observations because if `ABLFL` is `NA`, `ABLFL != "Y"` results in `NA` and not in `TRUE`.

**Comment by iqis** [comment]
This feel like an important difference pertinent to the audience.  Would @kaz462 take a look at this? 
Branch created.

**Comment by kaz462** [comment]
@iqis new section 3.18 is added right after 3.17 Creating new variables, please let me know if any issues with the current order. 

Content in sec 3.18
1. Brief summary of missing values between SAS and R, please help review.
2. Three examples of handling of missing values
- 3.1.8.1 Subsetting data: `!=` example @bundfussr mentioned above
- 3.1.8.2 Sorting data: an example from the recent admiral testing project
- 3.1.8.3 Creating new variables: missing`age` example @bundfussr mentioned above

Thanks @bundfussr, @iqis!
