### ISSUE TITLE
Cross-reference R package which allows to call SAS?

### ISSUE THREAD

**Issue by danielinteractive** [Bayer-Group/sas2r#8]
Hi, very interesting project, thanks for open sourcing!
We recently started to prototype https://github.com/insightsengineering/sasr
which is providing an R interface for running SAS commands and loading results back, via the `saspy` Python library.
Maybe that could be worth cross-referencing from here?
Thanks,
cheers
Daniel

**Comment by robertadamsbayer** [comment]
Hi @danielinteractive would be indeed nice to connect also here! What would you suggest? We could add a chapter about useful resources (additional to the usual links to R-resources) e.g. "associated open source projects" or so. And would a simple link / reference to the project be sufficient? Or would you even like to provide a short abstract describing more details about sasr?

**Comment by danielinteractive** [comment]
@robertadamsbayer Ah nice to meet you here! :-) 
that could be cool. or if you have any section already on calling R/SAS from each other that could fit as well.
Yes we could add 1-2 paragraphs

**Comment by robertadamsbayer** [comment]
There is no section yet but we can create one or... you make a pull request for a new chapter and provide your paragraphs already in .Rmd format - we have CI / CD pipeline in the background which should build the github pages with added chapters automatically (after reviewing of course). The intention of this project is to provide a living document that can be extended by everyone by adding .Rmd files via pull requests - would be an honor if you could be the first external contributor. There should be a manual for that in the pages or the github repo - let us also now if you find this confusing (we need to update then). If this is not possible, you could, of course, submit your paragaphs also directly to us then and we will make the updates.

**Comment by danielinteractive** [comment]
Cool thanks! @clarkliming maybe would you like to prepare a PR when you get the chance?

**Comment by iqis** [comment]
Is this also related? https://github.com/Hemken/SASmarkdown

**Comment by danielinteractive** [comment]
@iqis yes that is related too
